backend: serial
exp_name: mnist-pathological
algorithm: fedavg

dataset: MNIST
dataset_loader: torchvision
model_name: SimpleCNN

num_clients: 10
num_rounds: 2
num_sampled_clients: 5
split_type: pathological
min_classes: 2
local_epochs: 1
batch_size: 32

logging_backend: file
project_name: split-examples
experiment_name: mnist-pathological

log_dir: ./logs
data_dir: ./data
device: cpu
server_device: cpu
